services:
  dnshe-manager:
    image: ghcr.io/ryon718/dnshe-manager:latest
    container_name: dnshe-manager
    ports:
      - "8100:8080"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    # 自己改代码构建时取消下面注释，注释掉上面image
    # build: .
